---
- name: Clone todolist-flask and run
  hosts: all
  tasks:
    - name: Check if todolist-flask exists
      stat:
        path: /home/ubuntu/todolist-flask/
      register: dir_stat
    - name: Remove todolist-flask if it exists
      file:
        path: /home/ubuntu/todolist-flask/
        state: absent
      when: dir_stat.stat.exists
    - name: Clone todolist-flask
      git:
        repo: "https://github.com/andy-a-d-nguyen/todolist-flask.git"
        dest: /home/ubuntu/todolist-flask/
