---
- name: Clone todolist-flask and run
  hosts: all
  become: true
  tasks:
    - name: Check if todolist-flask exists
      stat:
        path: /home/ubuntu/todolist-flask/
      register: dir_stat
    - name: Remove todolist-flask if it exists
      file:
        path: /home/ubuntu/todolist-flask/
        state: absent
      when: dir_stat.stat.exists
    - name: Clone todolist-flask
      git:
        repo: "https://github.com/andy-a-d-nguyen/todolist-flask.git"
        dest: /home/ubuntu/todolist-flask/
    - name: Build todolist-flask
      command:
        chdir: /home/ubuntu/todolist-flask/
        cmd: docker build -t todolist-flask:latest .
    - name: Run todolist-flask
      command: |
        docker run -d \
        -e MYSQL_DATABASE_HOST=terraform-20250125145339070500000001.cvyw6igek2bp.us-east-1.rds.amazonaws.com \
        -e MYSQL_DATABASE_USER=andy \
        -e MYSQL_DATABASE_PASSWORD=andyandy \
        -p 80:80 \
        todolist-flask:latest
