---
- name: Set MySQL root password
  hosts: ubuntu_server
  become: yes
  vars:
    mysql_host: localhost
    mysql_username: andy
    mysql_password: andy
  tasks:
    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
    - name: Install Python MySQL library
      apt:
        name: python3-pymysql
        state: present
    - name: Create a ~/.my.cnf file for root user
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user = root
          socket = /var/run/mysqld/mysqld.sock
    - name: Create MySQL user andy
      mysql_user:
        host: "{{ mysql_host }}"
        name: "{{ mysql_username }}"
        password: "{{ mysql_password }}"
        priv: "*.*:ALL,GRANT"
        state: present
    - name: Set environment variables
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        create: yes
      with_items:
        - "MYSQL_DATABASE_HOST={{ mysql_host }}"
        - "MYSQL_DATABASE_USER={{ mysql_username }}"
        - "MYSQL_DATABASE_PASSWORD={{ mysql_password }}"
    - name: Create database
      mysql_db:
        name: todo_db
        state: present
    - name: Remove ~/.my.cnf file for security reasons
      file:
        path: /root/.my.cnf
        state: absent
