---
- name: Update and Upgrade Ubuntu Dependencies
  hosts: ubuntu_server
  become: true
  tasks:
    - name: Update Apt Package Index
      apt:
        update_cache: true
    - name: Upgrade All Packages
      apt:
        upgrade: dist
